name: Flutter Setup
description: Flutter Install & Get Dependencies

runs:
  using: composite
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: '3.32.8'
        cache: true
    - run: flutter --version
      shell: bash

    - name: Get dependencies
      run: flutter pub get
      shell: bash